apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  labels:
    component: fluentd
data:
  elasticsearch_username: elastic
  elasticsearch_password: ELASTIC_PASSWORD # it needs to be changed
