apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels:
    component: kibana
data:
  elasticsearch_username: elastic
  elasticsearch_password: ELASTIC_PASSWORD # it needs to be changed
